kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
    name: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      task: frontend
  template:
    metadata:
      labels:
        app: frontend
        task: frontend
    spec:
      containers:
        - name: frontend
          image: xitrum/frontend:1.3
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
  selector:
    app: frontend
    task: frontend
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: k3s-worker1
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000
    - host: k3s-worker2
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 3000                